config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  root 'static_pages#home'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dishes
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:dish_id/create"  => "favorites#create"
  delete "favorites/:dish_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  get :lists, to: 'lists#index'
  post   "lists/:dish_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
  resources :logs, only: [:create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @feed_items = current_user.feed.paginate(page: params[:page], per_page: 5)
      @log = Log.new
     end
   end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "クックログとは？") %>
<div id="fh5co-about">
  <div class="container">
    <div class="row">
      <div class="col-md-10">
        <h1 class="title-about">クックログとは？</h1>
        <h4>　自分が作った料理を、写真・メモ・材料などと共に記録できるサービスです。</h4>
      </div>
      <div class="col-md-10">
        <h2 class="title-use">主な使い方</h2>
        <div>
          <ol class="main-use">
            <li class="A">自分用のお料理ログとして使う</li>
            <li class="B">家族内でのお料理レパートリー共有サービスとして使う</li>
          </ol>
        </div>
        <p class="about-line"></p>
        <ol class="main-use">
          <li class="A">自分用のお料理ログとして使う</li>
        </ol>
        <div class="use-content">
          <p>　　作った料理をどんどん登録して、自分だけの料理レパートリーを作りましょう。</p>
          <p>　　「今日は何作ろう？」と迷ったら、</p>
          <p>　　次に作る料理を「お気に入り」や「作る予定リスト」から選んだり、</p>
          <p>　　使いたい材料を元に検索して探したりすることができます。</p>
        </div>
        <ol class="how-to-use">
          <li>新しい料理を写真やメモと共に追加</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）「新しい料理を作る」をクリックします。</p>
                <%= image_tag("/images/useA-1-1.jpg", :alt => "useA-1-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）料理情報を入力します。</p>
                <%= image_tag("/images/useA-1-2.jpg", :alt => "useA-1-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）料理の登録が完了しました！</p>
                <%= image_tag("/images/useA-1-3.jpg", :alt => "useA-1-3", class: "use-picture") %>
              </div>
              <div class="col-md-8">
                <p>料理には下記の情報を登録することができます。</p>
                <p>　・写真</p>
                <p>　・料理名</p>
                <p>　・説明</p>
                <p>　・分量</p>
                <p>　・材料（10種類まで）</p>
                <p>　・コツ・ポイント</p>
                <p>　・作り方参照用URL</p>
                <p>　・所要時間</p>
                <p>　・人気度</p>
                <p>　・クックメモ</p>
              </div>
            </div>
          </div>
          <li>登録済みの料理をまた作ったら、ログを追加</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）作る料理のページへ行き、クックログ追加部分を見つけます。</p>
                <%= image_tag("/images/useA-2-1.jpg", :alt => "useA-2-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）クックメモに、作った感想・次回作るときのためにメモしておきたい内容を入力し、「ログ追加」をクリックします。</p>
                <%= image_tag("/images/useA-2-2.jpg", :alt => "useA-2-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）クックログが追加されます。</p>
                <%= image_tag("/images/useA-2-3.jpg", :alt => "useA-2-3", class: "use-picture") %>
              </div>
            </div>
          </div>
          <li>作った料理を「お気に入りに登録」</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）「お気に入りに登録する」をクリックします。</p>
                <%= image_tag("/images/useA-3-1.jpg", :alt => "useA-3-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）メニューから「お気に入り」をクリックします。</p>
                <%= image_tag("/images/useA-3-2.jpg", :alt => "useA-3-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）お気に入り登録済みの料理を見ることができます。</p>
                <%= image_tag("/images/useA-3-3.jpg", :alt => "useA-3-3", class: "use-picture") %>
              </div>
            </div>
          </div>
          <li>登録済みの料理を「作る予定リスト」に追加</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）「作る予定リストに追加する」をクリックします。</p>
                <%= image_tag("/images/useA-4-1.jpg", :alt => "useA-4-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）メニューから「作る予定リスト」をクリックします。</p>
                <%= image_tag("/images/useA-4-2.jpg", :alt => "useA-4-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）作る予定リストに追加済みの料理を見ることができます。</p>
                <%= image_tag("/images/useA-4-3.jpg", :alt => "useA-4-3", class: "use-picture") %>
              </div>
            </div>
          </div>
          <li>登録済みの料理を検索</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）検索バーを見つけます。</p>
                <%= image_tag("/images/useA-5-1.jpg", :alt => "useA-5-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）探したい料理に関連するワード（例えば「肉」）を入力します。</p>
                <%= image_tag("/images/useA-5-2.jpg", :alt => "useA-5-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）料理名か材料名に「肉」を含む料理の一覧が表示されます。</p>
                <%= image_tag("/images/useA-5-3.jpg", :alt => "useA-5-3", class: "use-picture") %>
              </div>
            </div>
          </div>
        </ol>
        <ol class="main-use">
          <li class="B">家族内でのお料理レパートリー共有サービスとして使う</li>
        </ol>
        <div class="use-content">
          <p>　　例えば母親をフォローすれば、母親の料理レパートリーを一覧で見ることができます。</p>
          <p>　　食べて美味しかった料理をお気に入りに登録したり、コメントしたりできます。</p>
          <p>　　「食べたい！」リクエストを送れば、料理を作った人の「作る予定リスト」に追加されます。</p>
          <p>　　もちろん、自分で料理を作って登録することもできます。</p>
        </div>
        <ol class="how-to-use">
          <li>料理にコメント（またはお気に入り登録）</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）料理のページへ飛び、コメントを入力します。</p>
                <%= image_tag("/images/useB-1-1.jpg", :alt => "useB-1-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）コメントが追加されました！</p>
                <%= image_tag("/images/useB-1-2.jpg", :alt => "useB-1-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）コメント追加（またはお気に入り登録）すると、料理を作った人の通知メニューが赤くなり通知されます。</p>
                <%= image_tag("/images/useB-1-3.jpg", :alt => "useB-1-3", class: "use-picture") %>
              </div>
            </div>
            <div class="row">
              <div class="col-md-4">
                <p>（4）料理を作った人にお気に入り登録があった旨の通知が届いています。</p>
                <%= image_tag("/images/useB-1-4.jpg", :alt => "useB-1-4", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（5）料理を作った人にコメントがあった旨の通知が届いています。　　　</p>
                <%= image_tag("/images/useB-1-5.jpg", :alt => "useB-1-5", class: "use-picture") %>
              </div>
            </div>
          </div>
          <li>料理に「食べたい！」リクエストを送る</li>
          <div class="use-explanation">
            <div class="row">
              <div class="col-md-4">
                <p>（1）食べたい料理の「食べたいリクエストを送る」をクリックします。</p>
                <%= image_tag("/images/useB-2-1.jpg", :alt => "useB-2-1", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（2）料理を作った人がメニューから「作る予定リスト」をクリックします。</p>
                <%= image_tag("/images/useB-2-2.jpg", :alt => "useB-2-2", class: "use-picture") %>
              </div>
              <div class="col-md-4">
                <p>（3）「食べたいリクエスト」があったことがわかります。</p>
                <%= image_tag("/images/useB-2-3.jpg", :alt => "useB-2-3", class: "use-picture") %>
              </div>
            </div>
          </div>
        </ol>
      </div>
    </div>
  </div>
</div>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div id="fh5co-portfolio">
    <div class="container">
      <div class="col-md-9">
        <h3>みんなの料理 (<%= @feed_items.count %>)</h3>
        <%= render 'shared/feed' %>
      </div>
      <div class="col-md-3">
        <p><%= link_to "新しい料理を作る", new_dish_path, class: "btn btn-primary btn-lg btn-demo btn-record" %></p>
        <br>
        <p><%= link_to "みんなの料理をCSV出力", dishes_path(format: :csv), class: "btn btn-primary btn-lg btn-demo btn-csv" %></p>
      </div>
    </div>
  </div>
<% else %>
  <%= render 'shared/recruit_login' %>
  <header id="fh5co-header" class="fh5co-cover js-fullheight" role="banner">
    <div class="overlay"></div>
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2 text-center">
          <div class="display-t js-fullheight">
            <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
              <h1>毎日のお料理に、<br>写真やメモをつけて保存。</h1>
              <h2>今日のレシピ、もう迷わない！</h2>
              <p>
                <%= link_to 'クックログを始める', signup_path, class: "btn btn-primary btn-lg btn-demo" %>
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </header>
<% end %>

app/views/static_pages/terms.html.erb
<% provide(:title, "利用規約") %>
<div id="fh5co-about">
  <div class="container">
    <h1>利用規約</h1>
  </div>
</div>