config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  root 'static_pages#home'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dishes
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:dish_id/create"  => "favorites#create"
  delete "favorites/:dish_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  get :lists, to: 'lists#index'
  post   "lists/:dish_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
  resources :logs, only: [:create, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  has_many :dishes, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship",
                                  foreign_key: "follower_id",
                                  dependent: :destroy
  has_many :following, through: :active_relationships,  source: :followed
  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy
  has_many :followers, through: :passive_relationships, source: :follower
  has_many :favorites, dependent: :destroy
  has_many :notifications, dependent: :destroy
  has_many :lists, dependent: :destroy

  before_save :downcase_email
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  class << self
    # 渡された文字列のハッシュ値を返す
    def digest(string)
      cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                    BCrypt::Engine.cost
      BCrypt::Password.create(string, cost: cost)
    end

    # ランダムなトークンを返す
    def new_token
      SecureRandom.urlsafe_base64
    end
  end

  # 永続セッションのためにユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # 渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  # ユーザーのログイン情報を破棄する
  def forget
    update_attribute(:remember_digest, nil)
  end

  # フィード一覧を取得
  def feed
    Dish.where("user_id = ?", id)
  end

  # ユーザーをフォローする
  def follow(other_user)
    following << other_user
  end

  # ユーザーをフォロー解除する
  def unfollow(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  # 現在のユーザーがフォローしてたらtrueを返す
  def following?(other_user)
    following.include?(other_user)
  end
  
  # 現在のユーザーがフォローされていたらtrueを返す
  def followed_by?(other_user)
    followers.include?(other_user)
  end

  # ユーザーのステータスフィードを返す
  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE follower_id = :user_id"
    Dish.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  # 料理をお気に入りに登録する
  def favorite(dish)
    Favorite.create!(user_id: id, dish_id: dish.id)
  end
  
  # 料理をお気に入り解除する
  def unfavorite(dish)
    Favorite.find_by(user_id: id, dish_id: dish.id).destroy
  end
  
  # 現在のユーザーがお気に入り登録してたらtrueを返す
  def favorite?(dish)
    !Favorite.find_by(user_id: id, dish_id: dish.id).nil?
  end

  # 料理をリストに登録する
  def list(dish)
    List.create!(user_id: dish.user_id, dish_id: dish.id, from_user_id: id)
  end

  # 料理をリストから解除する
  def unlist(list)
    list.destroy
  end

  # 現在のユーザーがリスト登録してたらtrueを返す
  def list?(dish)
    !List.find_by(dish_id: dish.id, from_user_id: id).nil?
  end

  private
    def downcase_email
      self.email = email.downcase
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :show, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @dishes = @user.dishes.paginate(page: params[:page], per_page: 5)
    @log = Log.new
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "クックログへようこそ！"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params_update)
      flash[:success] = "プロフィールが更新されました!"
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    @user = User.find(params[:id])
    # 管理者ユーザーの場合
    if current_user.admin?
      @user.destroy
      flash[:success] = "ユーザーの削除に成功しました"
      redirect_to users_url
    # 管理者ユーザーではないが、自分のアカウントの場合
    elsif current_user?(@user)
      @user.destroy
      flash[:success] = "自分のアカウントを削除しました"
      redirect_to root_url
    else
      flash[:danger] = "他人のアカウントは削除できません"
      redirect_to root_url
    end
  end

  def following
    @title = "フォロー中"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "フォロワー"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private

  # ユーザー新規作成時に許可する属性
  def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
  end

  # プロフィール編集時に許可する属性
  def user_params_update
    params.require(:user).permit(:name, :email, :introduction, :sex)
  end

   # 正しいユーザーかどうか確認
  def correct_user
    @user = User.find(params[:id])
    if !current_user?(@user)
      flash[:danger] = "このページへはアクセスできません"
      redirect_to(root_url)
    end
  end  
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, size: 80, cl: "gravatar")
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: cl)
  end
end

app/views/users/_favorite.html.erb
<%= link_to "/favorites/#{@dish.id}/create",
            method: :post,
            class: 'like',
            remote: true do %>
  <div class="like-btn-like"><i class="fa fa-heart"></i> お気に入りに登録する</div>
<% end %>

app/views/users/_favorite_form.html.erb
<div id="favorite-<%= @dish.id %>">
  <% if !current_user.nil? && current_user.favorite?(@dish) %>
    <%= render 'users/unfavorite' %>
  <% else %>
    <%= render 'users/favorite' %>
  <% end %>
</div>

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "フォローする", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_list.html.erb
<%= link_to "/lists/#{@dish.id}/create",
            method: :post,
            class: 'list',
            remote: true do %>
  <% if current_user == @dish.user %>
    <div class="list-btn-list"><i class="fas fa-list-alt"></i> 作る予定リストに追加する</div>
  <% else %>
    <div class="list-btn-list"><i class="fas fa-utensils"></i> 食べたいリクエストを送る</div>
  <% end %>
<% end %>

app/views/users/_list_form.html.erb
<div id="list-<%= @dish.id %>" class="list-button">
  <% if !current_user.nil? && current_user.list?(@dish) %>
    <%= render 'users/unlist' %>
  <% else %>
    <%= render 'users/list' %>
  <% end %>
</div>

app/views/users/_unfavorite.html.erb
<%= link_to "/favorites/#{@dish.id}/destroy",
            method: :delete,
            class: 'unlike',
            remote: true do %>
  <div class="like-btn-unlike"><i class="fa fa-heart"></i> お気に入りに登録済み</div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "フォロー中", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
  <% if (current_user.admin? && current_user != user) || (!current_user.admin? && current_user == user) %>
    | <%= link_to "削除", user_path(user), method: :delete,
                                  data: { confirm: "本当に削除しますか？" } %>
  <% end %>
</li>

app/views/users/edit.html.erb
<% provide(:title, "プロフィール編集") %>
<div id="fh5co-portfolio">
  <div class="container">
    <%= link_to "プロフィール編集", edit_user_path %>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_for(@user) do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
        <div class="gravatar_edit">
          <%= gravatar_for(@user, size: 40) %>
          <%= @user.name %>
          <a href="http://gravatar.com/emails" target="_blank">プロフィール写真を変更</a>
        </div>
        <p></p>
        <div class = 'form-group'>
          <%= f.label :name %>　<span class="input-need">※必須</span>
          <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :email %>　<span class="input-need">※必須</span>
          <%= f.text_field :email, class: 'form-control', id: 'user_email' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :introduction %>　<span class="input-unneed">※任意</span>
          <%= f.text_area :introduction, size: "60x4", class: 'form-control', id: 'user_introduction' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :sex %>　<span class="input-unneed">※任意</span>
          <%= f.text_field :sex, class: 'form-control', id: 'user_sex' %>
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
        <p></p>
        <%= link_to "アカウントを削除する", user_path(@user), method: :delete,
                                    data: { confirm: "本当にこのアカウントを削除してよろしいですか？" } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'ユーザー一覧') %>
<div id="fh5co-portfolio">
  <div class="container">
    <h1>ユーザー一覧</h1>
    <%= will_paginate %>
    <ul class="users">
      <%= render @users %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/users/new.html.erb
<% provide(:title, "ユーザー登録") %>
<div id="fh5co-portfolio">
  <div class="container">
    <h1>ユーザー登録</h1>
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <%= form_with model: @user, local: true do |f| %>
          <%= render 'shared/error_messages', object: f.object %>
          <div class = 'form-group'>
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control', id: 'user_name' %>
          </div>
          <div class = 'form-group'>
            <%= f.label :email %>
            <%= f.email_field :email, class: 'form-control', id: 'user_email' %>
          </div>
          <div class = 'form-group'>
            <%= f.label :password %>
            <%= f.password_field :password, class: 'form-control', id: 'user_password' %>
          </div>
          <div class = 'form-group'>
            <%= f.label :password_confirmation %>
            <%= f.password_field :password_confirmation, class: 'form-control', id: 'user_password_confirmation' %>
          </div>
          <%= f.submit nil, class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, "プロフィール") %>
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row profile">
      <div class="col-md-9">
        <h3 class="title-profile">プロフィール</h3>
        <div class="row">
          <div class="col-md-4">
            <div class="user-picture-box">
              <%= gravatar_for @user, size: 120, cl: "gravatar user-picture" %>
            </div>
          </div>
          <div class="col-md-8">
            <h4 class="show-user-name"><%= @user.name %></h4>　<%= @user.sex %>
            <div class="show-user-introduction">
              <%= @user.introduction %>
            </div>
            <section class="stats">
              <%= render 'shared/stats' %>
            </section>
            <% if current_user == @user %>
              <div class="account-edit"><%= link_to "プロフィール編集", edit_user_path(@user) %></div>
            <% end %>
            <% if current_user.admin? || (current_user == @user) %>
              <div class="account-delete"><%= link_to "アカウント削除", user_path(@user), method: :delete,
                                            data: { confirm: "本当に削除しますか？" } %></div>
            <% end %>
            <br>
            <%= render 'follow_form' if logged_in? %>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-9">
        <% if @user.dishes.any? %>
          <h3>料理 (<%= @user.dishes.count %>)</h3>
          <ol class="dishes">
            <%= render @dishes %>
          </ol>
          <%= will_paginate @dishes %>
        <% end %>
      </div>
      <div class="col-md-3">
        <p><%= link_to "新しい料理を作る", new_dish_path, class: "btn btn-primary btn-lg btn-demo btn-record" %></p>
        <br>
        <p><%= link_to "みんなの料理をCSV出力", dishes_path(format: :csv), class: "btn btn-primary btn-lg btn-demo btn-csv" %></p>
      </div>
    </div>
  </div>
</div>

app/views/users/show_follow.html.erb
<% provide(:title, @title) %>
<div id="fh5co-portfolio">
  <div class="container">
    <div class="row">
      <aside class="col-md-4">
        <section class="user_info">
          <%= gravatar_for @user %>
          <h1><%= @user.name %></h1>
          <span><%= link_to "プロフィール", @user %></span>
          <span><b>料理</b><%= @user.dishes.count %><b>件</b></span>
        </section>
        <section class="stats">
          <%= render 'shared/stats' %>
          <% if @users.any? %>
            <div class="user_avatars">
              <% @users.each do |user| %>
                <%= link_to gravatar_for(user, size: 30), user %>
              <% end %>
            </div>
          <% end %>
        </section>
      </aside>
      <div class="col-md-8">
        <h3><%= @title %></h3>
        <% if @users.any? %>
          <ul class="users follow">
            <%= render @users %>
          </ul>
          <%= will_paginate %>
        <% end %>
      </div>
    </div>
  </div>
</div>