config/routes.rb
Rails.application.routes.draw do
  get 'lists/index'
  get 'sessions/new'
  get 'users/new'
  get 'users/show'
  get 'users/index'
  get    :login,     to: 'sessions#new'
  post   :login,     to: 'sessions#create'
  delete :logout,    to: 'sessions#destroy'
  root 'static_pages#home'
  get :signup,       to: 'users#new'
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :dishes
  get :about,        to: 'static_pages#about'
  get :use_of_terms, to: 'static_pages#terms'
  resources :relationships, only: [:create, :destroy]
  get :favorites, to: 'favorites#index'
  post   "favorites/:dish_id/create"  => "favorites#create"
  delete "favorites/:dish_id/destroy" => "favorites#destroy"
  resources :comments, only: [:create, :destroy]
  resources :notifications, only: :index
  get :lists, to: 'lists#index'
  post   "lists/:dish_id/create"  => "lists#create"
  delete "lists/:list_id/destroy" => "lists#destroy"
  resources :logs, only: [:create, :destroy]
end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="dishes">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_recruit_login.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-8 col-md-offset-2 text-center">
      <div class="display-t js-fullheight">
        <div class="display-tc js-fullheight animate-box" data-animate-effect="fadeIn">
          <div class="row recruit-login">
            <h3 class="title-form">【採用担当者様　専用ログインフォーム】</h3>
            <h4 class="description-form">下記の「専用ログイン」ボタンを押していただければ、<br>すぐに専用アカウントでログインが可能です。</h4>
            <div class="col-md-6 col-md-offset-3">
              <%= form_for(:session, url: login_path, local: true) do |f| %>
                <div class = 'form-group'>
                  <%= f.label 'メールアドレス' %>
                  <%= f.email_field :email, class: 'form-control', id: 'recruit_user_email', value: 'recruit@example.com' %>
                </div>
                <div class = 'form-group'>
                  <%= f.label 'パスワード' %>
                  <%= f.password_field :password, class: 'form-control', id: 'recruit_user_password', value: 'password' %>
                </div>
                <div class = 'form-group'>
                  <%= f.label :remember_me, class: "checkbox inline" do %>
                    <%= f.check_box :remember_me %>
                    <span>ログインしたままにする</span>
                  <% end %>
                </div>
                <%= f.submit '専用ログイン', class: 'btn btn-primary' %>
              <% end %>
              <div class="recruit-account">
                <p>＜採用担当者様　専用アカウント＞</p>
                <p>メールアドレス：recruit@example.com</p>
                <p>パスワード：password</p>
                <p>※フォームに予め入力済</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat"><%= @user.following.count %></strong>人をフォロー
  </a>　
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat"><%= @user.followers.count %></strong>人のフォロワー
  </a>
</div>